import styles from "../legal.module.css";
import { LegalFooter, LegalHeader } from "../terms/page";

const sections=[["controller","1. Operatorul"],["data","2. Date colectate"],["purposes","3. Scopuri și temeiuri"],["channels","4. Site și Telegram"],["sharing","5. Destinatari"],["transfers","6. Transferuri"],["retention","7. Păstrare"],["rights","8. Drepturile dvs."],["security","9. Securitate"],["cookies","10. Cookie-uri"],["children","11. Copii"],["changes","12. Contact și modificări"]];

export default function PrivacyPage(){return <main className={styles.page}><LegalHeader active="privacy"/><section className={styles.hero}><p className={styles.eyebrow}>LEGAL / ULTIMA ACTUALIZARE: 22 IULIE 2026</p><h1>Politica de confidențialitate</h1><p>Cum Quality Imports colectează, utilizează, păstrează și protejează datele personale atunci când folosiți site-ul, Telegram și serviciile de comandă.</p></section><div className={styles.body}><nav className={styles.toc} aria-label="Cuprins">{sections.map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</nav><article className={styles.content}>
<p className={styles.notice}><b>Notă înainte de lansarea comercială:</b> denumirea juridică, IDNO-ul și adresa operatorului de date trebuie completate după înregistrarea/confirmarea entității comerciale.</p>
<section id="controller"><h2>1. Cine este operatorul datelor</h2><p>Quality Imports stabilește scopurile și mijloacele prelucrării datelor aferente magazinului. Contact pentru confidențialitate și exercitarea drepturilor: <a href="mailto:qualityimportsmoldova@gmail.com">qualityimportsmoldova@gmail.com</a>. Serviciul este orientat către clienți din Republica Moldova.</p><p>Politica reflectă cadrul aplicabil la data actualizării, inclusiv Legea nr. 133/2011. Quality Imports își pregătește practicile pentru Legea nr. 195/2024, care, potrivit CNPDCP, intră în vigoare la 23 august 2026.</p></section>
<section id="data"><h2>2. Ce date colectăm</h2><ul><li><b>Date de identificare și contact:</b> nume, email, telefon, username și identificator Telegram.</li><li><b>Date despre comandă:</b> produse, SKU, cantități, preț, monedă, statut, sursă, adresă ori detalii de ridicare, comunicări și istoricul operațional.</li><li><b>Date despre plată:</b> statut, metodă, identificatorul tranzacției și linkul sesiunii. Nu stocăm numărul complet al cardului, PIN-ul sau CVV-ul.</li><li><b>Date de marketing:</b> alegerea separată de a primi noutăți și momentul consimțământului.</li><li><b>Date tehnice:</b> adresa IP și user-agent pot fi transmise prestatorului de plăți pentru securitate; furnizorii de hosting pot genera jurnale tehnice și de securitate.</li><li><b>Date despre personal:</b> emailul contului ChatGPT, rolul și evenimentele operaționale pentru utilizatorii autorizați.</li></ul></section>
<section id="purposes"><h2>3. De ce folosim datele și pe ce temei</h2><ul><li>Pentru a primi, verifica, confirma, încasa, livra, returna și gestiona comenzile — executarea contractului și demersuri la cererea clientului.</li><li>Pentru documente, evidențe contabile, obligații fiscale, garanții și răspunsuri către autorități — obligație legală.</li><li>Pentru prevenirea fraudei, securitatea serviciului, audit intern și apărarea drepturilor — interes legitim, evaluat față de drepturile persoanei.</li><li>Pentru noutăți și oferte — numai pe baza consimțământului separat, care poate fi retras oricând.</li><li>Pentru răspunsuri la întrebări și reclamații — contract, obligație legală sau interes legitim, după situație.</li></ul><p>Nu folosim datele comenzii pentru marketing doar fiindcă ați cumpărat. Nu efectuăm decizii cu efect juridic bazate exclusiv pe profilare automată.</p></section>
<section id="channels"><h2>4. Date primite prin site și Telegram</h2><p>Pe site, datele sunt furnizate în formularul de checkout. În Telegram, botul solicită emailul și telefonul și primește datele contului necesare conversației. Dacă folosiți butonul „Trimite numărul meu”, Telegram transmite botului numărul pe care ați ales să îl partajați. Politicile Telegram se aplică separat utilizării platformei.</p><p>Coșul site-ului este păstrat local în browser pentru continuitate. Coșul Telegram este menținut temporar de aplicația botului până la checkout ori restart. Datele devin înregistrare de comandă numai după trimiterea checkout-ului.</p></section>
<section id="sharing"><h2>5. Cui putem comunica datele</h2><p>Accesul este limitat la personalul QI autorizat și la furnizorii necesari: hosting și baze de date, Telegram pentru conversația botului, prestatorul de plăți maib după activare, furnizorul de email tranzacțional, curieri sau puncte de ridicare și consultanți profesionali. Furnizăm numai datele necesare rolului lor.</p><p>Putem divulga date când legea o cere, pentru protejarea drepturilor ori în cadrul unei reorganizări legitime, cu garanții corespunzătoare. Nu vindem date personale.</p></section>
<section id="transfers"><h2>6. Servicii și transferuri internaționale</h2><p>Unii furnizori tehnologici pot procesa date în afara Republicii Moldova. Înainte de activarea fiecărui furnizor, QI trebuie să verifice locația, rolul contractual și garanțiile aplicabile transferului. Folosim măsuri contractuale și tehnice adecvate și limităm datele transferate.</p></section>
<section id="retention"><h2>7. Cât timp păstrăm datele</h2><ul><li>Comenzile, plățile, livrările și documentele aferente: pe durata relației și ulterior cât cer obligațiile contabile, fiscale, de garanție și apărarea drepturilor.</li><li>Datele de marketing: până la retragerea consimțământului, dezabonare sau constatarea inactivității conform regulilor interne.</li><li>Conturile personalului: cât timp accesul este activ; evenimentele de audit pot fi păstrate ulterior pentru securitate și responsabilitate.</li><li>Jurnalele tehnice: pentru perioade scurte, proporționale cu securitatea și diagnosticarea.</li></ul><p>La expirarea termenului, datele sunt șterse, anonimizate sau izolate dacă păstrarea rămâne impusă de lege.</p></section>
<section id="rights"><h2>8. Drepturile persoanei</h2><p>În condițiile legii, puteți solicita informare și acces, corectare, ștergere sau blocare/restricționare, opoziție, retragerea consimțământului și informații despre destinatari. Odată cu aplicarea Legii nr. 195/2024, se vor aplica și drepturile consolidate prevăzute de aceasta, inclusiv portabilitatea acolo unde sunt îndeplinite condițiile.</p><p>Trimiteți cererea la adresa de contact, descriind dreptul și datele relevante. Putem cere informații rezonabile pentru verificarea identității. Retragerea consimțământului nu afectează legalitatea prelucrării anterioare și nu împiedică păstrarea datelor necesare unei obligații legale.</p><p>Aveți dreptul să depuneți plângere la <a href="https://datepersonale.md/" target="_blank" rel="noreferrer">Centrul Național pentru Protecția Datelor cu Caracter Personal</a> sau să folosiți celelalte remedii prevăzute de lege.</p></section>
<section id="security"><h2>9. Securitate și incidente</h2><p>Aplicăm control al accesului pe roluri, autentificare pentru paginile personalului, secrete de serviciu, verificarea callback-urilor de plată, conexiuni criptate și limitarea datelor accesibile. Nicio metodă nu elimină toate riscurile. Investigăm incidentele și notificăm persoanele ori autoritatea atunci când legea o cere.</p><p>Nu transmiteți prin email sau Telegram numărul complet al cardului, PIN, CVV, parole ori coduri bancare. Dacă suspectați un incident, contactați-ne imediat.</p></section>
<section id="cookies"><h2>10. Cookie-uri și stocare locală</h2><p>Magazinul nu utilizează în prezent cookie-uri de publicitate sau analiză comportamentală. Browserul păstrează local conținutul coșului pentru ca acesta să nu dispară la reîncărcare. Zonele personalului folosesc mecanisme de autentificare și sesiune furnizate de platforma de hosting/ChatGPT. Prestatorii externi pot folosi tehnologii strict necesare pe propriile pagini.</p><p>Dacă vom introduce analiză neesențială sau publicitate, vom actualiza politica și, unde este necesar, vom solicita alegerea utilizatorului înainte de activare.</p></section>
<section id="children"><h2>11. Datele copiilor</h2><p>Serviciul nu este conceput pentru colectarea intenționată a datelor copiilor fără implicarea reprezentantului legal. Dacă aflați că un copil a furnizat date necorespunzător, contactați-ne pentru examinare și ștergere, sub rezerva obligațiilor legale.</p></section>
<section id="changes"><h2>12. Contact și modificări</h2><p>Putem actualiza politica pentru schimbări de servicii, furnizori sau legislație. Vom afișa data versiunii și vom comunica separat schimbările importante când este necesar. Întrebări și cereri: <a href="mailto:qualityimportsmoldova@gmail.com">qualityimportsmoldova@gmail.com</a>.</p><p>Surse oficiale utile: <a href="https://datepersonale.md/" target="_blank" rel="noreferrer">CNPDCP</a> și <a href="https://www.legis.md/" target="_blank" rel="noreferrer">Registrul de stat al actelor juridice</a>.</p></section>
</article></div><LegalFooter/></main>}
