import styles from "../legal.module.css";
import Link from "next/link";

const sections = [
  ["operator", "1. Comerciantul"], ["scope", "2. Domeniul de aplicare"], ["products", "3. Produse și disponibilitate"],
  ["orders", "4. Comenzi și încheierea contractului"], ["prices", "5. Prețuri și plată"], ["delivery", "6. Livrare"],
  ["withdrawal", "7. Retragere și retur"], ["conformity", "8. Conformitatea produselor"], ["refunds", "9. Rambursări"],
  ["conduct", "10. Utilizarea serviciului"], ["liability", "11. Răspundere"], ["law", "12. Lege și reclamații"], ["changes", "13. Modificări"],
];

export default function TermsPage() {
  return <main className={styles.page}>
    <LegalHeader active="terms" />
    <section className={styles.hero}><p className={styles.eyebrow}>LEGAL / ULTIMA ACTUALIZARE: 22 IULIE 2026</p><h1>Termeni și condiții</h1><p>Condițiile aplicabile comenzilor plasate pe site-ul Quality Imports și prin botul oficial Telegram, pentru livrare în Republica Moldova.</p></section>
    <div className={styles.body}>
      <nav className={styles.toc} aria-label="Cuprins">{sections.map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</nav>
      <article className={styles.content}>
        <p className={styles.notice}><b>Notă importantă înainte de lansarea plăților:</b> denumirea juridică completă a comerciantului, IDNO-ul și adresa sediului trebuie adăugate aici și afișate înainte ca magazinul să accepte plăți comerciale.</p>
        <section id="operator"><h2>1. Comerciantul</h2><p>„Quality Imports”, „QI”, „noi” sau „comerciantul” desemnează operatorul magazinului online Quality Imports. Canal de contact pentru comenzi, retrageri, reclamații și întrebări: <a href="mailto:qualityimportsmoldova@gmail.com">qualityimportsmoldova@gmail.com</a>. Piața deservită este Republica Moldova. Datele juridice complete ale vânzătorului vor fi indicate și în confirmarea comenzii sau documentul fiscal aplicabil.</p></section>
        <section id="scope"><h2>2. Domeniul de aplicare</h2><p>Acești termeni se aplică utilizării site-ului, catalogului Telegram și comenzilor la distanță. Prin trimiterea unei comenzi, clientul confirmă că a citit acești termeni și că datele furnizate sunt corecte. Drepturile obligatorii acordate consumatorului de legislația Republicii Moldova nu sunt limitate prin acești termeni.</p><p>Serviciul este destinat persoanelor care au capacitatea juridică de a încheia contracte. Pentru un minor, comanda trebuie plasată sau aprobată de reprezentantul legal.</p></section>
        <section id="products"><h2>3. Produse și disponibilitate</h2><p>Descrierile, imaginile, mărimile, compoziția, autenticitatea declarată, prețul și statutul „în stoc” sau „precomandă” sunt prezentate cu bună-credință. Culorile pot varia în funcție de ecran. O eroare evidentă de preț, stoc sau descriere poate fi corectată înainte de acceptarea comenzii; clientul va fi informat și poate refuza condițiile corectate.</p><h3>Produse în stoc</h3><p>Statutul se reverifică la comandă. Adăugarea în coș nu rezervă produsul. Rezervarea începe numai după confirmarea comunicată de QI și poate expira dacă plata nu este efectuată în termenul indicat.</p><h3>Precomenzi</h3><p>Precomanda este o solicitare pentru un produs care urmează să fie procurat. Prețul final, termenul estimat și disponibilitatea sunt confirmate înainte de plată. Clientul poate refuza oferta confirmată.</p></section>
        <section id="orders"><h2>4. Comenzi și încheierea contractului</h2><p>Clientul selectează produsele și cantitățile, apoi furnizează numele, emailul, telefonul și datele de livrare. Mesajul automat „comandă primită” confirmă doar recepționarea solicitării, nu acceptarea ei.</p><p>Contractul de vânzare se consideră acceptat când QI confirmă disponibilitatea și transmite posibilitatea de plată, iar plata este confirmată, dacă părțile nu convin expres o altă modalitate. QI poate refuza sau anula o solicitare în caz de stoc insuficient, suspiciune rezonabilă de fraudă, date vădit incorecte, imposibilitate de livrare ori eroare evidentă. Orice sumă deja încasată pentru o comandă refuzată va fi rambursată.</p></section>
        <section id="prices"><h2>5. Prețuri și plată</h2><p>Prețurile sunt afișate în MDL. Costul livrării și orice cost obligatoriu suplimentar trebuie comunicate înainte de plata finală. Plata poate fi efectuată prin pagina securizată a prestatorului de plăți indicat la checkout sau, când este convenit, prin MIA ori transfer bancar către datele oficiale comunicate de QI.</p><p>QI nu solicită prin chat PIN-ul, CVV-ul, parola sau codurile de autorizare bancară. Plata este considerată efectuată numai după confirmarea prestatorului ori verificarea în contul comerciantului. O captură de ecran nu constituie singură dovadă finală a plății.</p></section>
        <section id="delivery"><h2>6. Livrare</h2><p>Livrarea se efectuează în Republica Moldova la adresa sau punctul de ridicare convenit. Termenul afișat pentru produsele în stoc este estimativ și începe după confirmarea plății. Pentru precomenzi, termenul se comunică separat. Clientul trebuie să furnizeze date complete și să fie disponibil pentru recepție.</p><p>Riscul trece la consumator când acesta sau persoana indicată de el intră în posesia fizică a produsului, conform regulilor obligatorii aplicabile. La primire, clientul este încurajat să verifice ambalajul și să ne comunice rapid orice lipsă sau deteriorare, fără ca această recomandare să restrângă drepturile legale.</p></section>
        <section id="withdrawal"><h2>7. Dreptul de retragere și returul</h2><p>În limitele legislației privind contractele la distanță, consumatorul poate notifica retragerea, fără a indica motivul, în termen de 14 zile calendaristice de la intrarea sa ori a persoanei desemnate în posesia fizică a produsului; pentru o singură comandă livrată separat, termenul curge de la ultimul produs.</p><p>Notificarea se transmite clar la <a href="mailto:qualityimportsmoldova@gmail.com">qualityimportsmoldova@gmail.com</a>, indicând numărul comenzii, produsul și datele de contact. Produsul trebuie returnat fără întârzieri nejustificate, în condițiile și termenul prevăzute de lege. Clientul răspunde numai pentru diminuarea valorii rezultată din manipulări ce depășesc verificarea naturii, caracteristicilor și funcționării produsului.</p><p>Costul direct al returului poate reveni clientului dacă acest lucru i-a fost comunicat înainte de comandă. Excepțiile legale de la retragere pot include, după caz, produse realizate după specificațiile clientului, produse personalizate sau produse sigilate care nu pot fi returnate din motive de protecție a sănătății ori igienă după desigilare. O excepție este aplicată numai dacă produsul și situația intră efectiv în categoria legală.</p></section>
        <section id="conformity"><h2>8. Produse neconforme, defecte sau greșite</h2><p>Dacă produsul este defect, neconform cu descrierea ori diferit de cel comandat, clientul trebuie să ne contacteze și să păstreze produsul și dovezile relevante. Remediile legale privind aducerea în conformitate, înlocuirea, reducerea prețului sau restituirea banilor se aplică în condițiile legislației. Drepturile pentru neconformitate sunt distincte de dreptul de retragere de 14 zile.</p></section>
        <section id="refunds"><h2>9. Rambursări și anulări</h2><p>Rambursarea eligibilă se face, de regulă, prin aceeași metodă de plată, cu excepția acordului expres pentru altă metodă și fără costuri nejustificate pentru client. Putem amâna rambursarea în limitele permise de lege până la recepționarea produsului returnat sau prezentarea dovezii expedierii. Termenele bancare de procesare nu sunt controlate de QI.</p><p>Înainte de plată, clientul poate solicita anularea. După expediere, se aplică regulile de retragere, retur și neconformitate.</p></section>
        <section id="conduct"><h2>10. Utilizarea serviciului</h2><p>Este interzisă utilizarea abuzivă a site-ului sau botului, plasarea de comenzi false, testarea neautorizată a securității, interferarea cu serviciul, accesarea zonelor pentru personal fără autorizare ori folosirea conținutului QI în scop fraudulos. Putem limita accesul și anula comenzile asociate unui abuz rezonabil documentat.</p><p>Textele, elementele de brand, fotografiile și designul aparțin QI sau licențiatorilor săi și nu pot fi reutilizate comercial fără permisiune.</p></section>
        <section id="liability"><h2>11. Disponibilitate și răspundere</h2><p>Depunem eforturi rezonabile pentru disponibilitatea serviciului, dar nu garantăm funcționarea fără întrerupere. În măsura permisă de lege, nu răspundem pentru întreruperi cauzate de furnizori externi, evenimente de forță majoră ori acțiuni din afara controlului rezonabil. Nicio clauză nu exclude răspunderea sau remediile care nu pot fi excluse față de consumator.</p><p>Linkurile externe, inclusiv către prestatori de plăți sau Telegram, sunt guvernate și de termenii acelor servicii.</p></section>
        <section id="law"><h2>12. Legea aplicabilă și reclamații</h2><p>Termenii sunt guvernați de legislația Republicii Moldova, inclusiv normele privind protecția consumatorilor și comerțul electronic. Trimiteți mai întâi reclamația la adresa de contact, cu numărul comenzii și soluția solicitată. Vom încerca soluționarea amiabilă într-un termen rezonabil. Consumatorul poate apela la autoritățile și instanțele competente, fără a pierde drepturile obligatorii acordate de lege.</p></section>
        <section id="changes"><h2>13. Modificări și contact</h2><p>Putem actualiza acești termeni pentru schimbări operaționale sau legislative. Versiunea aplicabilă unei comenzi este cea disponibilă la data plasării ei, cu excepția unei modificări impuse de lege. Pentru întrebări: <a href="mailto:qualityimportsmoldova@gmail.com">qualityimportsmoldova@gmail.com</a>.</p></section>
      </article>
    </div><LegalFooter />
  </main>;
}

function LegalHeader({active}:{active:"terms"|"privacy"}){return <header className={styles.header}><Link className={styles.brand} href="/"><span className={styles.mark}>QI</span><span>Quality Imports</span></Link><nav><Link href="/">Magazin</Link><Link className={active==="terms"?styles.active:""} href="/terms">Termeni</Link><Link className={active==="privacy"?styles.active:""} href="/privacy">Confidențialitate</Link></nav></header>}
export function LegalFooter(){return <footer className={styles.footer}><span>© 2026 Quality Imports · Republica Moldova</span><span><a href="mailto:qualityimportsmoldova@gmail.com">qualityimportsmoldova@gmail.com</a></span></footer>}
export {LegalHeader};
