"use client";

import { useMemo, useState } from "react";
import styles from "./resellers.module.css";

type Status = "pending" | "more_information" | "approved" | "rejected" | "suspended";
type Package = "none" | "starter" | "growth" | "strategic";
type Application = { id:string; contactName:string; businessName:string; email:string; phone:string; country:string; city:string; businessType:string; website:string|null; monthlyVolume:string; categories:string; registrationId:string|null; message:string|null; status:Status; resellerPackage:Package; customDiscount:number|null; internalNotes:string|null; reviewedBy:string|null; reviewedAt:string|null; createdAt:string; updatedAt:string };

const statusLabel: Record<Status,string> = { pending:"Pending", more_information:"More information", approved:"Approved", rejected:"Rejected", suspended:"Suspended" };

export default function ResellerManager({ initialApplications }: { initialApplications: Application[] }) {
  const [applications,setApplications]=useState(initialApplications); const [filter,setFilter]=useState<"all"|Status>("all"); const [open,setOpen]=useState<string>(""); const [busy,setBusy]=useState(""); const [message,setMessage]=useState("");
  const visible=useMemo(()=>applications.filter((item)=>filter==="all"||item.status===filter),[applications,filter]);
  async function refresh(){const response=await fetch("/api/staff/resellers");const result=await response.json();if(response.ok)setApplications(result.applications)}
  async function save(event:React.FormEvent<HTMLFormElement>,item:Application){event.preventDefault();setBusy(item.id);setMessage("");const data=new FormData(event.currentTarget);const rawDiscount=String(data.get("customDiscount")??"").trim();const response=await fetch("/api/staff/resellers",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:item.id,status:data.get("status"),resellerPackage:data.get("resellerPackage"),customDiscount:rawDiscount?Number(rawDiscount):null,internalNotes:data.get("internalNotes")})});const result=await response.json();setMessage(response.ok?"Reseller access updated.":result.error??"Update failed.");if(response.ok)await refresh();setBusy("")}
  return <section className={styles.workspace}><div className={styles.toolbar}><h2>Applications</h2><div>{(["all","pending","more_information","approved","rejected","suspended"] as const).map((value)=><button key={value} className={filter===value?styles.selected:""} onClick={()=>setFilter(value)}>{value==="all"?"All":statusLabel[value]}</button>)}</div></div>{message&&<p className={styles.message}>{message}</p>}
    {visible.length===0?<div className={styles.empty}><b>00</b><h3>No reseller applications in this view.</h3></div>:<div className={styles.list}>{visible.map((item)=><article key={item.id} className={styles.card}><button className={styles.summary} onClick={()=>setOpen(open===item.id?"":item.id)}><span><small>{new Date(item.createdAt).toLocaleDateString("ro-MD")}</small><b>{item.businessName}</b><em>{item.contactName} · {item.city}, {item.country}</em></span><span><i className={`${styles.status} ${styles[`status_${item.status}`]}`}>{statusLabel[item.status]}</i><b>{item.resellerPackage}</b><em>{item.monthlyVolume}</em></span><strong>{open===item.id?"−":"+"}</strong></button>
      {open===item.id&&<form className={styles.detail} onSubmit={(event)=>save(event,item)}><div className={styles.facts}><div><small>CONTACT</small><a href={`mailto:${item.email}`}>{item.email}</a><a href={`tel:${item.phone}`}>{item.phone}</a></div><div><small>BUSINESS</small><b>{item.businessType}</b><span>{item.registrationId||"No IDNO supplied"}</span>{item.website&&<a href={item.website} target="_blank">Open business page ↗</a>}</div><div><small>INTEREST</small><b>{item.categories}</b><span>{item.message||"No additional message"}</span></div></div><div className={styles.controls}><label>Status<select name="status" defaultValue={item.status}><option value="pending">Pending</option><option value="more_information">More information required</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="suspended">Suspended</option></select></label><label>Package<select name="resellerPackage" defaultValue={item.resellerPackage}><option value="none">None</option><option value="starter">Starter</option><option value="growth">Growth</option><option value="strategic">Strategic</option></select></label><label>Custom discount (%)<input name="customDiscount" type="number" min="0" max="60" defaultValue={item.customDiscount??""} placeholder="Use package default" /></label><label className={styles.notes}>Internal notes<textarea name="internalNotes" rows={4} defaultValue={item.internalNotes??""} /></label><button disabled={busy===item.id}>{busy===item.id?"Saving…":"Save reseller access"}</button></div></form>}</article>)}</div>}
  </section>;
}
